import { ALL_SLOTS, BASE16_SLOTS, deriveBase24, newId, type Palette, type System, type Theme, type Variant } from './scheme';

/** One entry of src/data/schemes.json (generated by scripts/import-schemes.mjs). */
export interface SchemeEntry {
  slug: string;
  system: System;
  name: string;
  author: string;
  description?: string;
  variant: Variant;
  /** Concatenated 6-digit hex values in slot order (16 or 24 of them). */
  colors: string;
}

export interface SchemeData {
  source: string;
  commit: string;
  date: string;
  schemes: SchemeEntry[];
}

let cache: Promise<SchemeData> | null = null;
/** The scheme collection is loaded lazily so it doesn't weigh on startup. */
export function loadSchemes(): Promise<SchemeData> {
  cache ??= import('../data/schemes.json').then((m) => m.default as SchemeData);
  return cache;
}

export function entryPalette(e: SchemeEntry): Palette {
  const palette = {} as Palette;
  const slots = e.system === 'base24' ? ALL_SLOTS : BASE16_SLOTS;
  slots.forEach((s, i) => (palette[s] = '#' + e.colors.slice(i * 6, i * 6 + 6)));
  if (e.system === 'base16') Object.assign(palette, deriveBase24(palette, e.variant));
  return palette;
}

export function creditLine(e: Pick<SchemeEntry, 'name' | 'author' | 'system'>): string {
  // Some upstream schemes leave the author blank; keep the credit truthful rather than guessing.
  return `Based on "${e.name}" (${e.system})` + (e.author ? ` by ${e.author}` : '');
}

/** The scheme as-is, e.g. for use as a comparison reference. */
export function entryTheme(e: SchemeEntry): Theme {
  return {
    id: newId(),
    name: e.name,
    author: e.author,
    slug: e.slug,
    description: e.description,
    system: e.system,
    variant: e.variant,
    palette: entryPalette(e),
    updatedAt: Date.now(),
  };
}

/** A new editable theme derived from a scheme, crediting the original. */
export function themeFromEntry(e: SchemeEntry): Theme {
  return {
    ...entryTheme(e),
    slug: undefined,
    description: creditLine(e),
    basedOn: { name: e.name, author: e.author, system: e.system, slug: e.slug },
  };
}

/** First-run theme (Tomorrow Night from tinted-theming/schemes, MIT). */
export const DEFAULT_ENTRY: SchemeEntry = {
  slug: 'tomorrow-night',
  system: 'base16',
  name: 'Tomorrow Night',
  author: 'Chris Kempson (http://chriskempson.com)',
  variant: 'dark',
  colors:
    '1d1f21282a2e373b41969896b4b7b4c5c8c6e0e0e0ffffff' +
    'cc6666de935ff0c674b5bd688abeb781a2beb294bba3685a',
};
